safe:        false
base-url:    /

source:      .
destination: ./_site

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   pretty      
#
# https://github.com/mojombo/jekyll/wiki/Permalinks
#
# Template Variables
# Variable  Description
# year   Year from the post’s filename
# month  Month from the post’s filename
# day  Day from the post’s filename
# title  Title from the post’s filename
# categories   The specified categories for this post. Jekyll automatically parses out double slashes in the URLs, so if no categories are present, it basically ignores this.   

# Built-in styles
# Name  Template
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title
# none  /:categories/:title.html

# Examples
# None specified. /2009/04/29/slap-chop.html
# permalink: pretty /2009/04/29/slap-chop/index.html
# permalink: /:month-:day-:year/:title.html /04-29-2009/slap-chop.html
# permalink: /blog/:year/:month/:day/:title /blog/2009/04/29/slap-chop/index.html

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: expanded  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)
    sass_dir: css
    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory

exclude: ['config.rb']

collections:
  things:
    output: true